name: PR Checks
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commit-lint:
    name: Lint Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: '.commitlint.config.mjs'

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Project checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Run Tests
        run: ./gradlew check

      - name: Build
        run: ./gradlew clean build